### PR TITLE
`transform_sqw` implementation

### LINKED ISSUE #402: Add transform sqw to the list of symop methods
Currently symop works together with cut_sqw_sym to build symmetrized cuts.  It would be beneficial for testing, code maintenance and cases where particular cuts need special treatment before combining  to be able to apply particular symmetry to the whole sqw object

CM 19/9/23: first sentence is no longer correct according to Alex

### PR DESCRIPTION
**Pull request by oerc0122**
Simple `symop` method to transform `sqw`, by transform of proj/pix. 

Possibly unnecessary and may not be used. 

Opening as draft for discussion.

Fixes #402

### CODE REVIEW

**Review by abuts — APPROVED** [review]
As it looks here, I have no objections

**Review by abuts — APPROVED** [review]
looks reasonable. Why it have  not merged yet?

**Comment by oerc0122** [comment]
Because I need to work out whether we actually want it.

**Comment by cmarooney-stfc** [comment]
closed with 402 as not needed any more

**Pull request closed without merging**
