### PR TITLE
delete permute_pix_array and to_slice, remove mention in doc #345

### PR DESCRIPTION
**Pull request by cmarooney-stfc**
As per ticket #345 remove permute_pix_array and to_slice, also delete mention of permute_pix_array from add docs

### CODE REVIEW

**Review by nickbattam-tessella — APPROVED** [review]
The advantages of deleting unused, untested functions is they need very few changes.

**Review by nickbattam-tessella — CHANGES_REQUESTED** [review]
The 02_sqw_current_implementation document still includes a reference to `to_slice` so that should be deleted if `permute_pix_array` is deleted. 

I wonder if that document should remain as (slightly unstructured) documentation of the original implementation rather than being updated to track the new implementation? 
If so, leaving these reference in perhaps striking them through would be more in the spirit of the document?

**Comment by cmarooney-stfc** [comment]
Strikethrough now pushed

**Comment by cmarooney-stfc** [comment]
Closed after merge with approval

**Pull request merged**
