### PR TITLE
Fix docify for R2024

### LINKED ISSUE #1780: Horace help does not work in Matlab 2024b
calling 
`>> help SymopRotation`
in Matlab 2023 returns some sencble output (though no help is actually there)
Trying to do the same in Matlab 2024b returns:
```
Unable to resolve the name 'matlab.internal.language.introspective.resolveName'.

Error in check_docify (line 5)
    resolver = matlab.internal.language.introspective.resolveName( ...
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in help (line 33)
        topic = check_docify(varargin{1});
                ^^^^^^^^^^^^^^^^^^^^^^^^^ 
```

### PR DESCRIPTION
**Pull request by mducle**
Fixes Horace overloaded `help` command using "docify" for R2024a and newer (where the Matlab internal language function `resolveName` changed package and syntax.

Fixes #1780

### CODE REVIEW

**Review by abuts — APPROVED** [review]
looks fine -- should be merged as soon as tests are passing. 

A unit test to check some small help would be useful

**Comment by mducle** [comment]
@abuts Thanks for adding the unit test... The CI runs are failing because the Matlab license server is currently offline due to a power supply upgrade in R89.

**Comment by mducle** [comment]
@abut ah... those were not _minor_ formatting changes! 

I think the changes make the code harder to read without the indentation and would very much prefer for them to be reverted please.

Also, you don't have to make a new commit to get the CI to build, you can just log into Jenkins and restart the job.

**Comment by abuts** [comment]
"@abut ah... those were not _minor_ formatting changes! 

I think the changes make the code harder to read without the indentation and would very much prefer for them to be reverted please."

I did standard Matlab identation (CTRL-A, CTRL-I). Its difficult without standard identation but this is what is everywhere in Horace.

Redrun job from login have recently been broken on Jenkins. Have not investigated why.

**Pull request merged**
